### ISSUE TITLE
E1 - Epic Example (8 pts)

### ISSUE THREAD

**Issue by hscrocha** [hscrocha/CS482_Fall23#2]
Example for an Epic or Big User Story with many pieces

- [x] Config the Server
- [x] Set up the Database
- [x] Front-end design
- [ ] Back-end functionality
- [ ] Unit Tests
